/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as PersonaRouteImport } from './routes/persona'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as CareRouteImport } from './routes/care'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsIdRouteImport } from './routes/programs.$id'
import { Route as MealsIdRouteImport } from './routes/meals.$id'
import { Route as ApiPublicLinePartnerWebhookRouteImport } from './routes/api/public/line.partner-webhook'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaRoute = PersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdRoute = ProgramsIdRouteImport.update({
  id: '/programs/$id',
  path: '/programs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsIdRoute = MealsIdRouteImport.update({
  id: '/meals/$id',
  path: '/meals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinePartnerWebhookRoute =
  ApiPublicLinePartnerWebhookRouteImport.update({
    id: '/api/public/line/partner-webhook',
    path: '/api/public/line/partner-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/care': typeof CareRoute
  '/channel': typeof ChannelRoute
  '/consent': typeof ConsentRoute
  '/expert': typeof ExpertRoute
  '/journey': typeof JourneyRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/persona': typeof PersonaRoute
  '/quest': typeof QuestRoute
  '/report': typeof ReportRoute
  '/meals/$id': typeof MealsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/programs/': typeof ProgramsIndexRoute
  '/api/public/line/partner-webhook': typeof ApiPublicLinePartnerWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/care': typeof CareRoute
  '/channel': typeof ChannelRoute
  '/consent': typeof ConsentRoute
  '/expert': typeof ExpertRoute
  '/journey': typeof JourneyRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/persona': typeof PersonaRoute
  '/quest': typeof QuestRoute
  '/report': typeof ReportRoute
  '/meals/$id': typeof MealsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/programs': typeof ProgramsIndexRoute
  '/api/public/line/partner-webhook': typeof ApiPublicLinePartnerWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/care': typeof CareRoute
  '/channel': typeof ChannelRoute
  '/consent': typeof ConsentRoute
  '/expert': typeof ExpertRoute
  '/journey': typeof JourneyRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/persona': typeof PersonaRoute
  '/quest': typeof QuestRoute
  '/report': typeof ReportRoute
  '/meals/$id': typeof MealsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/programs/': typeof ProgramsIndexRoute
  '/api/public/line/partner-webhook': typeof ApiPublicLinePartnerWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/care'
    | '/channel'
    | '/consent'
    | '/expert'
    | '/journey'
    | '/partner'
    | '/partners'
    | '/persona'
    | '/quest'
    | '/report'
    | '/meals/$id'
    | '/programs/$id'
    | '/programs/'
    | '/api/public/line/partner-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/care'
    | '/channel'
    | '/consent'
    | '/expert'
    | '/journey'
    | '/partner'
    | '/partners'
    | '/persona'
    | '/quest'
    | '/report'
    | '/meals/$id'
    | '/programs/$id'
    | '/programs'
    | '/api/public/line/partner-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/care'
    | '/channel'
    | '/consent'
    | '/expert'
    | '/journey'
    | '/partner'
    | '/partners'
    | '/persona'
    | '/quest'
    | '/report'
    | '/meals/$id'
    | '/programs/$id'
    | '/programs/'
    | '/api/public/line/partner-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CareRoute: typeof CareRoute
  ChannelRoute: typeof ChannelRoute
  ConsentRoute: typeof ConsentRoute
  ExpertRoute: typeof ExpertRoute
  JourneyRoute: typeof JourneyRoute
  PartnerRoute: typeof PartnerRoute
  PartnersRoute: typeof PartnersRoute
  PersonaRoute: typeof PersonaRoute
  QuestRoute: typeof QuestRoute
  ReportRoute: typeof ReportRoute
  MealsIdRoute: typeof MealsIdRoute
  ProgramsIdRoute: typeof ProgramsIdRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ApiPublicLinePartnerWebhookRoute: typeof ApiPublicLinePartnerWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona': {
      id: '/persona'
      path: '/persona'
      fullPath: '/persona'
      preLoaderRoute: typeof PersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id': {
      id: '/programs/$id'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/$id': {
      id: '/meals/$id'
      path: '/meals/$id'
      fullPath: '/meals/$id'
      preLoaderRoute: typeof MealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/line/partner-webhook': {
      id: '/api/public/line/partner-webhook'
      path: '/api/public/line/partner-webhook'
      fullPath: '/api/public/line/partner-webhook'
      preLoaderRoute: typeof ApiPublicLinePartnerWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CareRoute: CareRoute,
  ChannelRoute: ChannelRoute,
  ConsentRoute: ConsentRoute,
  ExpertRoute: ExpertRoute,
  JourneyRoute: JourneyRoute,
  PartnerRoute: PartnerRoute,
  PartnersRoute: PartnersRoute,
  PersonaRoute: PersonaRoute,
  QuestRoute: QuestRoute,
  ReportRoute: ReportRoute,
  MealsIdRoute: MealsIdRoute,
  ProgramsIdRoute: ProgramsIdRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ApiPublicLinePartnerWebhookRoute: ApiPublicLinePartnerWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
