/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as PersonaRouteImport } from './routes/persona'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as CareRouteImport } from './routes/care'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsIdRouteImport } from './routes/programs.$id'
import { Route as MealsIdRouteImport } from './routes/meals.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicLineLoginRouteImport } from './routes/api/public/line-login'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin.programs'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as ApiPublicLinePartnerWebhookRouteImport } from './routes/api/public/line.partner-webhook'
import { Route as ApiPublicLineCustomerWebhookRouteImport } from './routes/api/public/line.customer-webhook'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaRoute = PersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdRoute = ProgramsIdRouteImport.update({
  id: '/programs/$id',
  path: '/programs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsIdRoute = MealsIdRouteImport.update({
  id: '/meals/$id',
  path: '/meals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicLineLoginRoute = ApiPublicLineLoginRouteImport.update({
  id: '/api/public/line-login',
  path: '/api/public/line-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicLinePartnerWebhookRoute =
  ApiPublicLinePartnerWebhookRouteImport.update({
    id: '/api/public/line/partner-webhook',
    path: '/api/public/line/partner-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLineCustomerWebhookRoute =
  ApiPublicLineCustomerWebhookRouteImport.update({
    id: '/api/public/line/customer-webhook',
    path: '/api/public/line/customer-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/channel': typeof ChannelRoute
  '/consent': typeof ConsentRoute
  '/expert': typeof ExpertRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/persona': typeof PersonaRoute
  '/quest': typeof QuestRoute
  '/report': typeof ReportRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/meals/$id': typeof MealsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/programs/': typeof ProgramsIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/api/public/line-login': typeof ApiPublicLineLoginRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/line/customer-webhook': typeof ApiPublicLineCustomerWebhookRoute
  '/api/public/line/partner-webhook': typeof ApiPublicLinePartnerWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/channel': typeof ChannelRoute
  '/consent': typeof ConsentRoute
  '/expert': typeof ExpertRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/persona': typeof PersonaRoute
  '/quest': typeof QuestRoute
  '/report': typeof ReportRoute
  '/meals/$id': typeof MealsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/programs': typeof ProgramsIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/api/public/line-login': typeof ApiPublicLineLoginRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/line/customer-webhook': typeof ApiPublicLineCustomerWebhookRoute
  '/api/public/line/partner-webhook': typeof ApiPublicLinePartnerWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/care': typeof CareRoute
  '/channel': typeof ChannelRoute
  '/consent': typeof ConsentRoute
  '/expert': typeof ExpertRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/persona': typeof PersonaRoute
  '/quest': typeof QuestRoute
  '/report': typeof ReportRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/meals/$id': typeof MealsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/programs/': typeof ProgramsIndexRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/api/public/line-login': typeof ApiPublicLineLoginRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/line/customer-webhook': typeof ApiPublicLineCustomerWebhookRoute
  '/api/public/line/partner-webhook': typeof ApiPublicLinePartnerWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/channel'
    | '/consent'
    | '/expert'
    | '/journey'
    | '/login'
    | '/partner'
    | '/partners'
    | '/persona'
    | '/quest'
    | '/report'
    | '/admin'
    | '/meals/$id'
    | '/programs/$id'
    | '/programs/'
    | '/admin/bookings'
    | '/admin/programs'
    | '/api/public/line-login'
    | '/admin/'
    | '/api/public/line/customer-webhook'
    | '/api/public/line/partner-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/channel'
    | '/consent'
    | '/expert'
    | '/journey'
    | '/login'
    | '/partner'
    | '/partners'
    | '/persona'
    | '/quest'
    | '/report'
    | '/meals/$id'
    | '/programs/$id'
    | '/programs'
    | '/admin/bookings'
    | '/admin/programs'
    | '/api/public/line-login'
    | '/admin'
    | '/api/public/line/customer-webhook'
    | '/api/public/line/partner-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/care'
    | '/channel'
    | '/consent'
    | '/expert'
    | '/journey'
    | '/login'
    | '/partner'
    | '/partners'
    | '/persona'
    | '/quest'
    | '/report'
    | '/_authenticated/admin'
    | '/meals/$id'
    | '/programs/$id'
    | '/programs/'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/programs'
    | '/api/public/line-login'
    | '/_authenticated/admin/'
    | '/api/public/line/customer-webhook'
    | '/api/public/line/partner-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CareRoute: typeof CareRoute
  ChannelRoute: typeof ChannelRoute
  ConsentRoute: typeof ConsentRoute
  ExpertRoute: typeof ExpertRoute
  JourneyRoute: typeof JourneyRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  PartnersRoute: typeof PartnersRoute
  PersonaRoute: typeof PersonaRoute
  QuestRoute: typeof QuestRoute
  ReportRoute: typeof ReportRoute
  MealsIdRoute: typeof MealsIdRoute
  ProgramsIdRoute: typeof ProgramsIdRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ApiPublicLineLoginRoute: typeof ApiPublicLineLoginRoute
  ApiPublicLineCustomerWebhookRoute: typeof ApiPublicLineCustomerWebhookRoute
  ApiPublicLinePartnerWebhookRoute: typeof ApiPublicLinePartnerWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona': {
      id: '/persona'
      path: '/persona'
      fullPath: '/persona'
      preLoaderRoute: typeof PersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id': {
      id: '/programs/$id'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/$id': {
      id: '/meals/$id'
      path: '/meals/$id'
      fullPath: '/meals/$id'
      preLoaderRoute: typeof MealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/line-login': {
      id: '/api/public/line-login'
      path: '/api/public/line-login'
      fullPath: '/api/public/line-login'
      preLoaderRoute: typeof ApiPublicLineLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/line/partner-webhook': {
      id: '/api/public/line/partner-webhook'
      path: '/api/public/line/partner-webhook'
      fullPath: '/api/public/line/partner-webhook'
      preLoaderRoute: typeof ApiPublicLinePartnerWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/line/customer-webhook': {
      id: '/api/public/line/customer-webhook'
      path: '/api/public/line/customer-webhook'
      fullPath: '/api/public/line/customer-webhook'
      preLoaderRoute: typeof ApiPublicLineCustomerWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CareRoute: CareRoute,
  ChannelRoute: ChannelRoute,
  ConsentRoute: ConsentRoute,
  ExpertRoute: ExpertRoute,
  JourneyRoute: JourneyRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  PartnersRoute: PartnersRoute,
  PersonaRoute: PersonaRoute,
  QuestRoute: QuestRoute,
  ReportRoute: ReportRoute,
  MealsIdRoute: MealsIdRoute,
  ProgramsIdRoute: ProgramsIdRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ApiPublicLineLoginRoute: ApiPublicLineLoginRoute,
  ApiPublicLineCustomerWebhookRoute: ApiPublicLineCustomerWebhookRoute,
  ApiPublicLinePartnerWebhookRoute: ApiPublicLinePartnerWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
