// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// ============================================================================
// Types
// ============================================================================

interface AuthMiddlewareContext {
  headers: Record<string, string>;
  token?: string;
}

// ============================================================================
// Constants
// ============================================================================

const AUTHORIZATION_HEADER = "Authorization";
const BEARER_PREFIX = "Bearer ";

// ============================================================================
// Helper Functions
// ============================================================================

function logAuthEvent(event: string, details?: Record<string, unknown>): void {
  if (process.env.NODE_ENV === "development") {
    console.debug(`[SupabaseAuth] ${event}`, details);
  }
}

function isTokenExpired(token: string): boolean {
  try {
    // Decode JWT payload (base64)
    const payload = token.split(".")[1];
    if (!payload) return true;

    const decoded = JSON.parse(atob(payload));
    const exp = decoded.exp;

    if (!exp) return false;

    // Check if token expires in less than 5 minutes
    const expiresIn = exp * 1000 - Date.now();
    return expiresIn < 5 * 60 * 1000;
  } catch {
    return true;
  }
}

async function refreshTokenIfNeeded(): Promise<string | null> {
  try {
    const {
      data: { session },
      error,
    } = await supabase.auth.refreshSession();

    if (error) {
      logAuthEvent("refresh-failed", { error: error.message });
      return null;
    }

    if (session?.access_token) {
      logAuthEvent("refreshed", { hasToken: !!session.access_token });
      return session.access_token;
    }

    return null;
  } catch (error) {
    logAuthEvent("refresh-error", {
      error: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}

// ============================================================================
// Main Middleware
// ============================================================================

/**
 * Supabase authentication middleware for TanStack Start.
 * Attaches the user's access token to serverFn requests.
 *
 * Must be registered as a global `functionMiddleware` in `src/start.ts`.
 * This ensures the browser attaches the bearer token to serverFn RPCs.
 */
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const startTime = Date.now();

    try {
      // Get current session
      const {
        data: { session },
        error: sessionError,
      } = await supabase.auth.getSession();

      if (sessionError) {
        logAuthEvent("session-error", { error: sessionError.message });
        return next({ headers: {} });
      }

      let token = session?.access_token;

      // Check if token needs refresh
      if (token && isTokenExpired(token)) {
        logAuthEvent("token-expired", { willRefresh: true });
        const newToken = await refreshTokenIfNeeded();
        if (newToken) {
          token = newToken;
        }
      }

      const duration = Date.now() - startTime;
      const hasToken = !!token;

      logAuthEvent("middleware", { hasToken, durationMs: duration });

      // Attach token to request headers
      const headers: Record<string, string> = {};
      if (token) headers[AUTHORIZATION_HEADER] = `${BEARER_PREFIX}${token}`;

      return next({ headers });
    } catch (error) {
      logAuthEvent("unexpected-error", {
        error: error instanceof Error ? error.message : String(error),
      });

      // Fall through without auth on error
      return next({ headers: {} });
    }
  },
);

// ============================================================================
// Server-side Helper
// ============================================================================

/**
 * Server-side version of auth middleware.
 * Use this for server-only function middleware.
 *
 * @example
 * export const myServerFn = createServerFn({ method: 'POST' })
 *   .middleware([attachSupabaseAuth.server])
 *   .handler(async ({ context }) => {
 *     const userId = context.userId;
 *     // ...
 *   });
 */
export const attachSupabaseAuthServer = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const { getRequest } = await import("@tanstack/react-start/server");
    const request = getRequest();
    const authHeader = request.headers.get(AUTHORIZATION_HEADER);
    const token = authHeader?.startsWith(BEARER_PREFIX)
      ? authHeader.slice(BEARER_PREFIX.length)
      : null;

    logAuthEvent("server-middleware", { hasToken: !!token });

    return next({
      context: { token },
    });
  },
);

// ============================================================================
// Helper to get user from context
// ============================================================================

/**
 * Extract user information from authenticated request context.
 * Use this in server function handlers.
 */
export async function getUserFromContext(context: { token?: string }) {
  if (!context.token) {
    return { user: null, error: "No authentication token" };
  }

  try {
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser(context.token);

    if (error) {
      logAuthEvent("get-user-error", { error: error.message });
      return { user: null, error: error.message };
    }

    return { user, error: null };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logAuthEvent("get-user-exception", { error: message });
    return { user: null, error: message };
  }
}

// ============================================================================
// Default Export
// ============================================================================

export default {
  attachSupabaseAuth,
  attachSupabaseAuthServer,
  getUserFromContext,
};
