// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// ============================================================================
// Types
// ============================================================================

interface AuthContext {
  supabase: ReturnType<typeof createClient<Database>>;
  userId: string;
  claims: Record<string, unknown>;
  email?: string;
}

interface TokenClaims {
  sub: string;
  email?: string;
  aud?: string;
  exp?: number;
  iat?: number;
  [key: string]: unknown;
}

// ============================================================================
// Constants
// ============================================================================

const AUTHORIZATION_HEADER = "authorization";
const BEARER_PREFIX = "Bearer ";
const TOKEN_REFRESH_THRESHOLD_MS = 5 * 60 * 1000; // 5 minutes

// ============================================================================
// Helper Functions
// ============================================================================

function logAuthEvent(event: string, details?: Record<string, unknown>): void {
  if (process.env.NODE_ENV === "development") {
    console.debug(`[SupabaseAuth] ${event}`, details);
  }
}

function logAuthError(event: string, error: unknown): void {
  const errorMessage = error instanceof Error ? error.message : String(error);
  console.error(`[SupabaseAuth] ${event} failed:`, errorMessage);
}

function validateEnvironmentVariables(): void {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  const missing: string[] = [];

  if (!SUPABASE_URL) missing.push("SUPABASE_URL");
  if (!SUPABASE_PUBLISHABLE_KEY) missing.push("SUPABASE_PUBLISHABLE_KEY");

  // Service role key is optional for auth middleware, but warn if missing
  if (!SUPABASE_SERVICE_ROLE_KEY && process.env.NODE_ENV === "production") {
    console.warn("[SupabaseAuth] SUPABASE_SERVICE_ROLE_KEY not set - some admin operations may fail");
  }

  if (missing.length > 0) {
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[SupabaseAuth] ${message}`);
    throw new Error(message);
  }
}

function extractTokenFromRequest(request: Request): string | null {
  const authHeader = request.headers.get(AUTHORIZATION_HEADER);

  if (!authHeader) {
    logAuthEvent("no-auth-header");
    return null;
  }

  if (!authHeader.startsWith(BEARER_PREFIX)) {
    logAuthEvent("invalid-auth-scheme", { scheme: authHeader.split(" ")[0] });
    return null;
  }

  const token = authHeader.slice(BEARER_PREFIX.length);
  if (!token || token.length === 0) {
    logAuthEvent("empty-token");
    return null;
  }

  return token;
}

function isTokenExpired(claims: TokenClaims): boolean {
  if (!claims.exp) return false;

  const expiresAt = claims.exp * 1000;
  const now = Date.now();

  return now >= expiresAt - TOKEN_REFRESH_THRESHOLD_MS;
}

function getTokenExpiryMessage(claims: TokenClaims): string {
  if (!claims.exp) return "unknown expiry";

  const expiresAt = claims.exp * 1000;
  const now = Date.now();
  const remainingMs = expiresAt - now;

  if (remainingMs <= 0) return "expired";

  const remainingMinutes = Math.floor(remainingMs / 60000);
  return `expires in ${remainingMinutes} minutes`;
}

// ============================================================================
// Main Middleware
// ============================================================================

/**
 * Supabase authentication middleware for TanStack Start server functions.
 * Validates Bearer token and attaches Supabase client with user context.
 *
 * Must be registered as middleware in server functions.
 *
 * @example
 * export const myServerFn = createServerFn({ method: 'POST' })
 *   .middleware([requireSupabaseAuth])
 *   .handler(async ({ context }) => {
 *     const { supabase, userId, claims } = context;
 *     // Use authenticated client
 *   });
 */
export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(async ({ next }) => {
  const startTime = Date.now();

  // 1. Validate environment
  validateEnvironmentVariables();

  const SUPABASE_URL = process.env.SUPABASE_URL!;
  const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY!;

  // 2. Get request object
  let request: Request;
  try {
    request = getRequest();
  } catch (error) {
    logAuthError("get-request", error);
    throw new Error("Unauthorized: Unable to access request context");
  }

  if (!request?.headers) {
    throw new Error("Unauthorized: No request headers available");
  }

  // 3. Extract and validate token
  const token = extractTokenFromRequest(request);
  if (!token) {
    throw new Error("Unauthorized: No valid authorization token provided");
  }

  // 4. Create Supabase client with token
  const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      headers: {
        Authorization: `${BEARER_PREFIX}${token}`,
      },
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });

  // 5. Verify token and get claims
  let claims: TokenClaims | null = null;
  let userId: string | null = null;

  try {
    const { data, error } = await supabase.auth.getUser(token);

    if (error) {
      logAuthError("get-user", error);
      throw new Error(`Unauthorized: ${error.message}`);
    }

    if (!data?.user) {
      throw new Error("Unauthorized: No user data returned");
    }

    userId = data.user.id;
    claims = {
      sub: data.user.id,
      email: data.user.email,
      aud: data.user.app_metadata?.provider_id,
    };

    logAuthEvent("token-verified", {
      userId: userId.slice(0, 8),
      email: data.user.email,
    });
  } catch (error) {
    // Try alternative method with getClaims
    try {
      const { data, error } = await supabase.auth.getClaims(token);

      if (error || !data?.claims) {
        throw new Error("Invalid token");
      }

      claims = data.claims as TokenClaims;
      userId = claims.sub;

      if (!userId) {
        throw new Error("No user ID found in token");
      }

      logAuthEvent("token-claims-verified", {
        userId: userId.slice(0, 8),
        expiry: getTokenExpiryMessage(claims),
      });
    } catch (claimsError) {
      logAuthError("token-validation", claimsError);
      throw new Error("Unauthorized: Invalid or expired token");
    }
  }

  // 6. Check token expiry
  if (claims && isTokenExpired(claims)) {
    logAuthEvent("token-expired", { userId: userId?.slice(0, 8) });
    throw new Error("Unauthorized: Token has expired");
  }

  // 7. Create authenticated client for the request
  const authClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      headers: {
        Authorization: `${BEARER_PREFIX}${token}`,
      },
    },
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  });

  const duration = Date.now() - startTime;
  logAuthEvent("authenticated", {
    userId: userId?.slice(0, 8),
    durationMs: duration,
  });

  // 8. Return context with authenticated client
  return next({
    context: {
      supabase: authClient,
      userId: userId!,
      claims: claims || {},
      email: claims?.email,
    } as AuthContext,
  });
});

// ============================================================================
// Optional: Require Admin Role Middleware
// ============================================================================

/**
 * Extends requireSupabaseAuth to also require admin role.
 * Use this for admin-only server functions.
 */
export const requireAdminAuth = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const { supabase, userId } = context as AuthContext;

    const { data, error } = await supabase.from("user_roles").select("role").eq("user_id", userId).maybeSingle();

    if (error) {
      throw new Error(`Unauthorized: Unable to verify admin status - ${error.message}`);
    }

    if (data?.role !== "admin") {
      throw new Error("Forbidden: Admin role required");
    }

    return next();
  });

// ============================================================================
// Helper: Get user from context
// ============================================================================

export function getUserFromAuthContext(context: unknown): { userId: string; email?: string } | null {
  const ctx = context as AuthContext;
  if (!ctx?.userId) return null;
  return { userId: ctx.userId, email: ctx.email };
}

// ============================================================================
// Default Export
// ============================================================================

export default {
  requireSupabaseAuth,
  requireAdminAuth,
  getUserFromAuthContext,
};
